name: Build and deploy Python project to Azure Function App - manishorderfunc

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ''   # empty means “root of unzipped folder”
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # needed for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create zip package
        run: |
          # Zip every file at repo root, excluding your venv folder and .github/
          zip -r release.zip . -x "venv_order_processor/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write      # needed for azure/login
      contents: read       # needed for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip package
        run: unzip release.zip -d ./zipped

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZUREAPPSERVICE_CLIENTID_296276FEDEB84871B3C1B93A128859D3 }}
          tenant-id:     ${{ secrets.AZUREAPPSERVICE_TENANTID_EBEB5D26C9114C389C82DDD2FD992911 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B25FC456A0374C8396A9277B85D6631D }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:  'manishorderfunc'
          slot-name: 'Production'
          package:   './zipped'
